---
title: "Plant Community Wrangling"
output: html_document
date: "2023-06-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)


```

```{r}
survey_1A_2023_04_12 = read_csv(here("data/2023/plant_community/surveys/survey_1A_2023_04_12.csv"))
```
```{r}
survey= survey_1A_2023_04_12 %>%
  pivot_longer(cols = c(cover1, cover2, cover3, cover4, cover5, cover6))%>%
  rename(cover = name, species = value)
```


```{r}
survey_counts <- survey %>%
  pivot_longer(cols = c(cover1count, cover2count, cover3count, cover4count, cover5count,      cover6count), values_to ="count")%>%
  mutate(name = str_replace(name, "count", ""))%>%
  filter(name == cover)%>% #is the first thing equal to the thing
   drop_na()%>%
  select(-name)
```


```{r}
species_summary = survey_counts%>%  #create new dataframe from survey_counts to make species summary with only four columns
  group_by(treatment, block, quad, species)%>% #creates new table given certain columns
  summarize(total_count = sum(count))%>% #added the counts per species to create the count total
  mutate(relative_cover = total_count/sum(total_count))%>% #relative count is the total count in eahc row divided by the sum of all the counts 
  mutate(absolute_cover = total_count/25)%>%
  rename(plot = block)
  
```

```{r}
leaf_scans = read_csv(here("data","2023","sedgwick_leaf_scans_20230421", "Summary1.csv"))
```
```{r}
leaf_dry_mass= read_csv(here("data", "2023", "traits", "leaf_dry_mass.csv"))
```
```{r}
leaf_scans_formatted = leaf_scans %>% 
  clean_names()%>%
 separate(slice, into = c("plot", "species"), sep="-") %>%
  mutate(species= str_sub(species, start= 1, end = 4), 
         species= tolower(species), 
         plot= as.numeric(plot))

```


```{r}
leaf_scan_and_dry_mass = leaf_scans_formatted %>%
  left_join(leaf_dry_mass, by= c("plot", "species"))%>%
  mutate(sla= total_area/leaf_dry_mass)
```

```{r}
leaf_CN = read_csv(here("data","2023","traits", "leaf_CN_20230620.csv"))
```

```{r}
leaf_CN_formatted = leaf_CN %>%
  clean_names()%>%
   rename(sample_ID = sample, mass= mass,leaf_nitrogen= nitrogen, leaf_carbon = carbon) %>%
   separate(sample_ID, into = c("plot", "species"), sep="-")%>%
  drop_na(species)%>%
  select("plot","species", "mass", "leaf_nitrogen", "leaf_carbon")

```

```{r}
leaf_CN_formatted <- leaf_CN_formatted %>%
  mutate(CNratio=leaf_carbon/leaf_nitrogen, plot= as.numeric(plot))%>%
  left_join(leaf_scan_and_dry_mass, by= c("plot", "species"))
  
```

##### This is where you need to calculate average N per species before the next chunk of code. Then you can do a left_join by species

```{r}
leaf_CN_and_species_summary_data = species_summary %>%
   left_join(leaf_CN_formatted, by= c("species","plot"))

```

#### You're calculating species averages in the chunk below - after you joined the leaf CN data. Use the code you wrote here but on the leaf_CN_formatted dataframe above

```{r}
species_avg_N= leaf_CN_and_species_summary_data %>%
  group_by(species)%>%
  summarize(species_avg_N = mean(leaf_nitrogen))
```


```{r}
species_avg_N_join = species_avg_N %>%
  left_join(leaf_CN_and_species_summary_data, by= c("species"))%>%
  group_by(plot, treatment, quad)
```

```{r}
species_weighted_N= species_avg_N_join %>%
  mutate(leaf_N_weighted_avg = species_avg_N*relative_cover)%>%
  summarize(average_N = sum(leaf_N_weighted_avg)/14)%>%
  group_by(plot, treatment, quad)
```

