---
title: "SLA Code"
output: html_document
date: "2023-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
```

```{r}
leaf_scans = read_csv(here("data","2023","sedgwick_leaf_scans_20230421", "Summary1.csv"))
```
```{r}
leaf_dry_mass= read_csv(here("data", "2023", "traits", "leaf_dry_mass.csv"))
```
```{r}
leaf_scans_formatted = leaf_scans %>% 
  clean_names()%>%
 separate(slice, into = c("plot", "species"), sep="-") %>%
  mutate(species= str_sub(species, start= 1, end = 4), 
         species= tolower(species), 
         plot= as.numeric(plot))

```


```{r}
leaf_scan_and_dry_mass = leaf_scans_formatted %>%
  left_join(leaf_dry_mass, by= c("plot", "species"))%>%
  mutate(sla= total_area/leaf_dry_mass)
```


```{r}
ggplot(leaf_scan_and_dry_mass, aes(x = species, y= sla))+
  geom_boxplot()
ggplot(leaf_scan_and_dry_mass, aes(x=species, y=sla, fill=species)) + 
    geom_boxplot(alpha=0.3) +
    theme(legend.position="none")

```


```{r}
leaf_CN = read_csv(here("data","2023","traits", "leaf_CN_20230620.csv"))
```

```{r}
leaf_CN_formatted = leaf_CN %>%
  clean_names()%>%
   rename(sample_ID = sample, mass= mass,leaf_nitrogen= nitrogen, leaf_carbon = carbon) %>%
   separate(sample_ID, into = c("plot", "species"), sep="-")%>%
  drop_na(species)%>%
  select("plot","species", "mass", "leaf_nitrogen", "leaf_carbon")

```

```{r}
leaf_CN_formatted <- leaf_CN_formatted %>%
  mutate(CNratio=leaf_carbon/leaf_nitrogen, plot= as.numeric(plot))%>%
  left_join(leaf_scan_and_dry_mass, by= c("plot", "species"))
  
```

```{r}
ggplot(leaf_CN_formatted, aes(x=leaf_nitrogen, y=sla, color = species)) +  geom_point()

```

